
version: '3'

services:

  syrus:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    image: syrus-0.1
    container_name: syrus
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
    networks:
      - syrus-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8180:8180"
    volumes:
      - ./:/var/www
      - ./config/docker/nginx:/etc/nginx/conf.d
      - ./config/docker/nginx:/var/log/nginx
    networks:
      - syrus-network

#Docker Networks
networks:
  syrus-network:
    driver: bridge


